import { getCanonicalProductHref, getPublicHref } from '../../../lib/navigation'
import type { DiscoverabilityLink } from '../types/discoverability'

export const relatedServicesByKey: Record<string, DiscoverabilityLink[]> = {
  rotulacion: [
    {
      id: 'vehicle-design',
      title: 'Diseno grafico para vehiculos',
      description: 'Base visual para ordenar logo, mensajes, cobertura y lectura comercial antes de instalar.',
      href: '#/contacto',
      label: 'Servicio',
      tag: 'Design',
    },
    {
      id: 'vinilo-comercial',
      title: 'Vinilo comercial',
      description: 'Soportes, acabados y laminados para vehiculos, cristales y punto de venta.',
      href: getCanonicalProductHref('vinilo'),
      label: 'Relacionado',
      tag: 'Vinilo',
    },
    {
      id: 'escaparates',
      title: 'Rotulacion de escaparates',
      description: 'Extiende la visibilidad de vehiculo a cristal, fachada y senaletica comercial.',
      href: getPublicHref('carteleria'),
      label: 'Relacionado',
      tag: 'Retail',
    },
    {
      id: 'empresa-cards',
      title: 'Tarjetas de empresa',
      description: 'Material comercial complementario para visitas, reparto y seguimiento presencial.',
      href: getCanonicalProductHref('tarjetas'),
      label: 'Upsell',
      tag: 'Papeleria',
    },
    {
      id: 'empresa-dtf',
      title: 'DTI uniformes empresa',
      description: 'Conecta la rotulacion del vehiculo con textil corporativo y presencia de equipo.',
      href: getCanonicalProductHref('dtf'),
      label: 'Relacionado',
      tag: 'Textil',
    },
    {
      id: 'branding-stickers',
      title: 'Pegatinas branding',
      description: 'Aplicaciones rapidas para packaging, showroom, eventos y entregas.',
      href: '#/catalogo',
      label: 'Relacionado',
      tag: 'Sticker',
    },
  ],
  dtf: [
    {
      id: 'camisetas-personalizadas',
      title: 'Camisetas personalizadas',
      description: 'Salida natural del DTF cuando el cliente necesita soporte textil ademas del transfer.',
      href: getCanonicalProductHref('textil'),
      label: 'Relacionado',
      tag: 'Textil',
    },
    {
      id: 'sudaderas',
      title: 'Sudaderas',
      description: 'Pieza de valor mayor para eventos, uniforme y venta de marca.',
      href: getCanonicalProductHref('textil'),
      label: 'Upsell',
      tag: 'Apparel',
    },
    {
      id: 'uniformes',
      title: 'Uniformes empresa',
      description: 'DTF conectado con ropa laboral y branding de equipo.',
      href: getCanonicalProductHref('textil'),
      label: 'Relacionado',
      tag: 'Empresa',
    },
    {
      id: 'packs-empresa',
      title: 'Packs empresa',
      description: 'Combina textil, pegatinas, tarjetas y rotulacion bajo una misma narrativa comercial.',
      href: '#/catalogo',
      label: 'Bundle',
      tag: 'Cross-sell',
    },
    {
      id: 'etiquetas-textiles',
      title: 'Etiquetas textiles',
      description: 'Complemento de acabado para series cortas o produccion de marca.',
      href: getCanonicalProductHref('vinilo'),
      label: 'Relacionado',
      tag: 'Acabado',
    },
  ],
  pegatinas: [
    {
      id: 'packaging',
      title: 'Packaging y etiquetas',
      description: 'Cruce natural para negocios que usan pegatinas como parte del packaging o entrega.',
      href: getCanonicalProductHref('vinilo'),
      label: 'Relacionado',
      tag: 'Packaging',
    },
    {
      id: 'tarjetas',
      title: 'Tarjetas empresa',
      description: 'Pieza comercial complementaria para marca local y eventos.',
      href: getCanonicalProductHref('tarjetas'),
      label: 'Upsell',
      tag: 'Papeleria',
    },
    {
      id: 'vinilo-escaparate',
      title: 'Vinilo para escaparate',
      description: 'Lleva el branding adhesivo desde etiqueta a punto de venta.',
      href: getPublicHref('carteleria'),
      label: 'Relacionado',
      tag: 'Retail',
    },
    {
      id: 'branding-local',
      title: 'Branding local',
      description: 'Combinacion util para negocios de proximidad con visibilidad fisica.',
      href: getCanonicalProductHref('rotulacion'),
      label: 'Bundle',
      tag: 'Marca',
    },
  ],
}
