import type { ArtworkProductRule, ArtworkProductRuleKey } from '../types/artworkUpload'

export const artworkProductRules: Record<ArtworkProductRuleKey, ArtworkProductRule> = {
  business_cards: {
    key: 'business_cards',
    label: 'Tarjetas',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG'],
    maxFileSizeMb: 50,
    recommendedMinResolutionDpi: 300,
    recommendedPhysicalSizeLabel: '91 × 61 mm con sangrado',
    helperCopy: 'Sangrado 3 mm y textos a 3-5 mm del corte.',
    guide: {
      bleedMm: 3,
      safeMarginMm: 4,
      innerMarginMm: 6,
      showCutline: true,
      showSafeZone: true,
      showBleedZone: true,
      previewMode: 'sheet',
      preferredOrientation: 'landscape',
      aspectRatio: 91 / 61,
    },
    recommendations: [
      'Extiende los fondos hasta la zona de sangrado.',
      'Mantén textos y logos dentro de la zona segura.',
    ],
  },
  stickers: {
    key: 'stickers',
    label: 'Pegatinas',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG'],
    maxFileSizeMb: 80,
    recommendedMinResolutionDpi: 300,
    recommendedPhysicalSizeLabel: 'Formato final con contorno de corte',
    helperCopy: 'Conviene dejar sangrado y línea de corte vectorial.',
    guide: {
      bleedMm: 2,
      safeMarginMm: 3,
      innerMarginMm: 4,
      showCutline: true,
      showSafeZone: true,
      showBleedZone: true,
      previewMode: 'sheet',
      preferredOrientation: 'free',
      aspectRatio: 1,
    },
    recommendations: [
      'Para pegatinas recomendamos una línea de corte vectorial clara.',
      'Deja un margen de seguridad para evitar cortes sobre texto.',
    ],
  },
  dtf_meter: {
    key: 'dtf_meter',
    label: 'DTF por metro',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG', 'TIFF', 'ZIP'],
    maxFileSizeMb: 250,
    recommendedMinResolutionDpi: 300,
    recommendedPhysicalSizeLabel: 'Rollo 58-60 cm de ancho útil',
    helperCopy: 'Mantén separación entre diseños y revisa el ancho útil del rollo.',
    guide: {
      bleedMm: 0,
      safeMarginMm: 8,
      innerMarginMm: 12,
      showCutline: false,
      showSafeZone: true,
      showBleedZone: false,
      previewMode: 'roll',
      preferredOrientation: 'portrait',
      aspectRatio: 0.58,
    },
    recommendations: [
      'Para DTF deja separación entre diseños antes de fabricar.',
      'Si el archivo va muy justo de ancho, revisa el aprovechamiento del rollo.',
    ],
  },
  printed_vinyl: {
    key: 'printed_vinyl',
    label: 'Vinilo impreso',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG', 'TIFF'],
    maxFileSizeMb: 120,
    recommendedMinResolutionDpi: 150,
    recommendedPhysicalSizeLabel: 'Medida final + sangrado de montaje',
    helperCopy: 'Revisa escala, orientación y área visible.',
    guide: {
      bleedMm: 5,
      safeMarginMm: 8,
      innerMarginMm: 10,
      showCutline: true,
      showSafeZone: true,
      showBleedZone: true,
      previewMode: 'vinyl',
      preferredOrientation: 'landscape',
      aspectRatio: 1.6,
    },
    recommendations: [
      'Añade sangrado suficiente para el montaje.',
      'Comprueba que textos y logos queden fuera de zonas de remate.',
    ],
  },
  signage: {
    key: 'signage',
    label: 'Cartelería',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG', 'TIFF'],
    maxFileSizeMb: 150,
    recommendedMinResolutionDpi: 120,
    recommendedPhysicalSizeLabel: 'Formato grande según distancia de lectura',
    helperCopy: 'La resolución depende del tamaño final y de la distancia de lectura.',
    guide: {
      bleedMm: 5,
      safeMarginMm: 10,
      innerMarginMm: 14,
      showCutline: true,
      showSafeZone: true,
      showBleedZone: true,
      previewMode: 'sheet',
      preferredOrientation: 'landscape',
      aspectRatio: 1.4,
    },
    recommendations: [
      'A mayor formato, comprueba la resolución efectiva antes de imprimir.',
      'Deja margen seguro para textos cerca del borde.',
    ],
  },
  textile: {
    key: 'textile',
    label: 'Textil',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG'],
    maxFileSizeMb: 80,
    recommendedMinResolutionDpi: 300,
    recommendedPhysicalSizeLabel: 'Tamaño final de marcaje',
    helperCopy: 'Comprueba tamaño de estampación y legibilidad final.',
    guide: {
      bleedMm: 0,
      safeMarginMm: 4,
      innerMarginMm: 6,
      showCutline: false,
      showSafeZone: true,
      showBleedZone: false,
      previewMode: 'sheet',
      preferredOrientation: 'free',
      aspectRatio: 1,
    },
    recommendations: [
      'Si el arte incluye textos pequeños, revisa legibilidad a tamaño real.',
      'Podemos revisar manualmente el archivo si no tienes versión final.',
    ],
  },
  paper: {
    key: 'paper',
    label: 'Papelería',
    acceptedFormats: ['PDF', 'AI', 'EPS', 'SVG', 'PNG', 'JPG', 'JPEG'],
    maxFileSizeMb: 80,
    recommendedMinResolutionDpi: 300,
    recommendedPhysicalSizeLabel: 'Formato final con sangrado',
    helperCopy: 'Papelería con sangrado y zona segura visibles.',
    guide: {
      bleedMm: 3,
      safeMarginMm: 4,
      innerMarginMm: 6,
      showCutline: true,
      showSafeZone: true,
      showBleedZone: true,
      previewMode: 'sheet',
      preferredOrientation: 'portrait',
      aspectRatio: 0.7,
    },
    recommendations: [
      'Mantén la información sensible dentro de la zona segura.',
      'Extiende fondos e imágenes hasta el sangrado.',
    ],
  },
}
