import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const accessoryBaseFields: ConfiguratorField[] = [
  { key: 'product', type: 'variant', label: 'Producto', required: true, options: [] },
  { key: 'quantity', type: 'quantity', label: 'Cantidad', required: true, min: 50, step: 50 },
]

export const accesoriosEntries: CatalogEntry[] = [
  {
    id: 'llavero-6x6',
    slug: 'llavero-6x6',
    kind: 'product',
    category: 'accesorios',
    name: 'Llavero 6 x 6 cm',
    description: 'Llavero de metacrilato cortado a laser en tirada de 1000 unidades.',
    shortDescription: 'Accesorio con tirada fija y paso directo al carrito.',
    route: '#/producto/accesorios',
    purchaseMode: 'direct',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [
      { key: 'product', type: 'variant', label: 'Producto', required: true, options: [] },
      { key: 'quantity', type: 'quantity', label: 'Tirada', required: true, min: 1000, step: 1000 },
    ],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/accesorios', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'tirada',
    tiers: [{ min: 1000, max: 1000, totalPrice: 150 }],
    catalogGroups: ['direct'],
    visualKey: 'stickers',
  },
  {
    id: 'llavero-8x8',
    slug: 'llavero-8x8',
    kind: 'product',
    category: 'accesorios',
    name: 'Llavero 8 x 8 cm',
    description: 'Llavero de metacrilato 8 x 8 cm en tirada de 1000 unidades.',
    shortDescription: 'Accesorio ampliado con precio por tirada definida.',
    route: '#/producto/accesorios',
    purchaseMode: 'direct',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [
      { key: 'product', type: 'variant', label: 'Producto', required: true, options: [] },
      { key: 'quantity', type: 'quantity', label: 'Tirada', required: true, min: 1000, step: 1000 },
    ],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/accesorios', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'tirada',
    tiers: [{ min: 1000, max: 1000, totalPrice: 170 }],
    catalogGroups: ['direct'],
    visualKey: 'stickers',
  },
  {
    id: 'pegatina-sin-laminar',
    slug: 'pegatina-sin-laminar',
    kind: 'product',
    category: 'accesorios',
    name: 'Pegatina 10 x 10 sin laminar',
    description: 'Pegatina ecosolvente sin laminar con tiradas cortas.',
    shortDescription: 'Pegatina directa con escalado por cantidad.',
    route: '#/producto/accesorios',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...accessoryBaseFields, { key: 'file', type: 'file', label: 'Archivo', accept: '.pdf,.ai,.eps,.svg,.png,.jpg,.jpeg' }],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/accesorios', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'ud',
    tiers: [
      { min: 50, max: 50, unitPrice: 2.5 },
      { min: 100, max: 100, unitPrice: 2.2 },
      { min: 200, max: 200, unitPrice: 1.9 },
      { min: 300, max: 300, unitPrice: 1.7 },
    ],
    catalogGroups: ['direct'],
    visualKey: 'stickers',
  },
  {
    id: 'pegatina-laminada',
    slug: 'pegatina-laminada',
    kind: 'product',
    category: 'accesorios',
    name: 'Pegatina 10 x 10 laminada',
    description: 'Pegatina laminada con acabado mate o brillo.',
    shortDescription: 'Pegatina laminada con tiradas definidas y cierre directo.',
    route: '#/producto/accesorios',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...accessoryBaseFields, { key: 'file', type: 'file', label: 'Archivo', accept: '.pdf,.ai,.eps,.svg,.png,.jpg,.jpeg' }],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/accesorios', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'tirada',
    tiers: [
      { min: 100, max: 100, totalPrice: 90 },
      { min: 200, max: 200, totalPrice: 160 },
      { min: 300, max: 300, totalPrice: 220 },
    ],
    catalogGroups: ['direct'],
    visualKey: 'stickers',
  },
]
