import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const materialFields: ConfiguratorField[] = [
  { key: 'product', type: 'variant', label: 'Material', required: true, options: [] },
  { key: 'area', type: 'area', label: 'Superficie', required: true, min: 0.1, step: 0.1 },
]

export const materialesEntries: CatalogEntry[] = [
  {
    id: 'vinilo-monomerico',
    slug: 'vinilo-monomerico',
    kind: 'product',
    category: 'materiales',
    name: 'Vinilo monomerico',
    description: 'Vinilo monomerico por metro cuadrado.',
    shortDescription: 'Material directo por m2 para piezas sencillas de fabricacion.',
    route: '#/producto/materiales',
    purchaseMode: 'hybrid',
    pricingMode: 'm2',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...materialFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/materiales', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'm2',
    basePrice: 80,
    catalogGroups: ['direct', 'gran-formato'],
    visualKey: 'storefront',
  },
  {
    id: 'vinilo-microperforado',
    slug: 'vinilo-microperforado',
    kind: 'product',
    category: 'materiales',
    name: 'Vinilo microperforado',
    description: 'Vinilo microperforado homologado por metro cuadrado.',
    shortDescription: 'Material homologado por m2 para lunas y piezas tecnicas.',
    route: '#/producto/materiales',
    purchaseMode: 'hybrid',
    pricingMode: 'm2',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...materialFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/materiales', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'm2',
    basePrice: 85,
    catalogGroups: ['direct', 'gran-formato'],
    visualKey: 'storefront',
  },
  {
    id: 'vinilo-polimerico',
    slug: 'vinilo-polimerico',
    kind: 'product',
    category: 'materiales',
    name: 'Vinilo polimerico',
    description: 'Vinilo polimerico por metro cuadrado.',
    shortDescription: 'Vinilo de mayor resistencia con lectura por superficie.',
    route: '#/producto/materiales',
    purchaseMode: 'hybrid',
    pricingMode: 'm2',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...materialFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/materiales', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'm2',
    basePrice: 90,
    catalogGroups: ['direct', 'gran-formato'],
    visualKey: 'storefront',
  },
  {
    id: 'vinilo-pared',
    slug: 'vinilo-pared',
    kind: 'product',
    category: 'materiales',
    name: 'Vinilo pared',
    description: 'Vinilo de pared por metro cuadrado.',
    shortDescription: 'Decoracion mural por m2 con comprobacion tecnica posterior.',
    route: '#/producto/materiales',
    purchaseMode: 'hybrid',
    pricingMode: 'm2',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...materialFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/materiales', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'm2',
    basePrice: 100,
    catalogGroups: ['direct', 'gran-formato'],
    visualKey: 'storefront',
  },
]
