import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const paperFields: ConfiguratorField[] = [
  { key: 'product', type: 'variant', label: 'Producto', required: true, options: [] },
  { key: 'quantity', type: 'quantity', label: 'Tirada', required: true, min: 100, step: 50 },
  { key: 'file', type: 'file', label: 'Archivo', accept: '.pdf,.ai,.eps,.svg,.png,.jpg,.jpeg' },
  { key: 'notes', type: 'textarea', label: 'Notas', rows: 4 },
]

export const papeleriaEntries: CatalogEntry[] = [
  {
    id: 'tarjetas-estandar',
    slug: 'tarjetas-estandar',
    kind: 'product',
    category: 'papeleria',
    name: 'Tarjetas 8,5 x 5,5 cm',
    description: 'Tarjetas estandar con tramos de tirada del catalogo 2026.',
    shortDescription: 'Tarjetas por tirada con opcion de diseno y propuesta comercial.',
    route: '#/producto/papeleria',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats], notes: ['El diseno puede presupuestarse aparte.'] },
    configuratorFields: [...paperFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/papeleria', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'tirada',
    productionTime: '4-5 dias habiles.',
    notes: ['Diseno de tarjetas: 35 EUR/hora.', 'Mismo precio para 1 cara o 2 caras.'],
    tiers: [
      { min: 100, max: 100, totalPrice: 40 },
      { min: 250, max: 250, totalPrice: 50 },
      { min: 500, max: 500, totalPrice: 60 },
      { min: 1000, max: 1000, totalPrice: 85 },
      { min: 2500, max: 2500, totalPrice: 105 },
      { min: 5000, max: 5000, totalPrice: 135 },
    ],
    catalogGroups: ['direct'],
  },
  {
    id: 'flyer-a6',
    slug: 'flyer-a6',
    kind: 'product',
    category: 'papeleria',
    name: 'Flyer A6',
    description: 'Flyer tamano A6 con tramos por tirada del catalogo 2026.',
    shortDescription: 'Flyers por tirada con lectura directa y comprobacion de archivo.',
    route: '#/producto/papeleria',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...paperFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/papeleria', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'tirada',
    productionTime: '4-5 dias habiles.',
    notes: ['Mismo precio para 1 cara o 2 caras.'],
    tiers: [
      { min: 100, max: 100, totalPrice: 85 },
      { min: 250, max: 250, totalPrice: 90 },
      { min: 500, max: 500, totalPrice: 100 },
      { min: 1000, max: 1000, totalPrice: 110 },
      { min: 2500, max: 2500, totalPrice: 130 },
      { min: 5000, max: 5000, totalPrice: 165 },
    ],
    catalogGroups: ['direct'],
  },
  {
    id: 'flyer-a5',
    slug: 'flyer-a5',
    kind: 'product',
    category: 'papeleria',
    name: 'Flyer A5',
    description: 'A5, A4 y A3 quedan preparados para consulta comercial segun tirada.',
    shortDescription: 'Papeleria ampliada sujeta a cantidad, formato y propuesta comercial.',
    route: '#/producto/papeleria',
    purchaseMode: 'quote',
    pricingMode: 'quote',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...paperFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=papeleria', label: 'Solicitar presupuesto', serviceKey: 'papeleria' },
    manualReviewRequired: true,
    badge: 'Consultar',
    notes: ['Consultar medidas y cantidades para otras variantes de flyers.'],
    catalogGroups: ['quote'],
  },
]
