import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const baseFields: ConfiguratorField[] = [
  { key: 'product', type: 'variant', label: 'Producto', required: true, options: [], hint: 'Compara prendas sin salir de la pagina.' },
  { key: 'quantity', type: 'quantity', label: 'Cantidad', required: true, min: 1, step: 1, hint: 'La estimacion se ajusta por tramo de volumen.' },
]

export const textilEntries: CatalogEntry[] = [
  {
    id: 'camiseta-basica',
    slug: 'camiseta-basica-estampada',
    kind: 'product',
    category: 'textil',
    name: 'Camiseta basica estampada',
    description: 'Camiseta 100% algodon con estampado delante y atras segun el catalogo 2026.',
    shortDescription: 'Camisetas con tramos por volumen y lectura comercial directa.',
    route: '#/producto/textil',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...baseFields, { key: 'notes', type: 'textarea', label: 'Notas', rows: 4 }],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/textil', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    badge: 'Textil',
    unitLabel: 'ud',
    productionTime: '24-48h o 5 dias habiles si traen prenda.',
    notes: ['Incluye delante y atras.', '+2 EUR por estampado adicional.'],
    tiers: [
      { min: 1, max: 1, unitPrice: 25, note: '1 sola camiseta' },
      { min: 8, max: 19, unitPrice: 13, note: 'Mas de 8 prendas' },
      { min: 20, unitPrice: 12, note: 'Mas de 20 prendas' },
    ],
    catalogGroups: ['direct', 'textil'],
    visualKey: 'textile',
  },
  {
    id: 'camiseta-premium',
    slug: 'camiseta-premium-estampada',
    kind: 'product',
    category: 'textil',
    name: 'Camiseta premium estampada',
    description: 'Version premium 100% algodon con tramos por volumen.',
    shortDescription: 'Linea premium por volumen con cierre rapido o consulta comercial.',
    route: '#/producto/textil',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...baseFields, { key: 'notes', type: 'textarea', label: 'Notas', rows: 4 }],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/textil', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    badge: 'Textil',
    unitLabel: 'ud',
    productionTime: 'Segun stock y comprobacion del pedido.',
    notes: ['+3 EUR por estampado adicional.'],
    tiers: [
      { min: 1, max: 5, unitPrice: 35, note: 'Menos de 6 prendas' },
      { min: 6, max: 13, unitPrice: 32, note: 'Mas de 6 prendas' },
      { min: 14, unitPrice: 28, note: 'Mas de 14 prendas' },
    ],
    catalogGroups: ['direct', 'textil'],
    visualKey: 'textile',
  },
  {
    id: 'gorra-camionero',
    slug: 'gorra-camionero',
    kind: 'product',
    category: 'textil',
    name: 'Gorra camionero',
    description: 'Modelo camionero con tramo por volumen.',
    shortDescription: 'Gorras por volumen con paso directo al carrito.',
    route: '#/producto/textil',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...baseFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/textil', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'ud',
    tiers: [
      { min: 1, max: 7, unitPrice: 10 },
      { min: 8, unitPrice: 8 },
    ],
    catalogGroups: ['direct', 'textil'],
    visualKey: 'textile',
  },
  {
    id: 'polo-corto',
    slug: 'polo-manga-corta',
    kind: 'product',
    category: 'textil',
    name: 'Polo manga corta',
    description: 'Polo manga corta con tramos por volumen.',
    shortDescription: 'Polos preparados para tiradas rapidas con comprobacion posterior.',
    route: '#/producto/textil',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...baseFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/textil', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'ud',
    tiers: [
      { min: 1, max: 7, unitPrice: 18 },
      { min: 8, unitPrice: 17 },
    ],
    catalogGroups: ['direct', 'textil'],
    visualKey: 'textile',
  },
  {
    id: 'sudadera',
    slug: 'sudadera-estampada',
    kind: 'product',
    category: 'textil',
    name: 'Sudadera',
    description: 'Sudadera con tarifa directa por volumen.',
    shortDescription: 'Sudaderas para tiradas directas con verificacion posterior.',
    route: '#/producto/textil',
    purchaseMode: 'hybrid',
    pricingMode: 'volume',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [...baseFields],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'add_to_cart', href: '#/producto/textil', label: 'Anadir al carrito' },
    manualReviewRequired: true,
    unitLabel: 'ud',
    tiers: [
      { min: 1, max: 7, unitPrice: 20 },
      { min: 8, unitPrice: 18 },
    ],
    catalogGroups: ['direct', 'textil'],
    visualKey: 'textile',
  },
]
