import type { SearchKeywordGroup } from '../types/searchIntelligence'

export const keywordGroups: SearchKeywordGroup[] = [
  {
    id: 'dtf-meter-core',
    label: 'DTF por metro',
    primaryTerm: 'DTF por metro',
    variants: ['DTI por metro', 'impresion DTF', 'DTF textil', 'DTF Barcelona', 'DTF Blanes'],
    intents: ['transactional', 'commercial', 'local'],
    entity: 'dtf',
    stage: 'decide',
    priority: 'high',
    localities: ['barcelona', 'blanes', 'girona', 'costa-brava', 'espana'],
    relatedServices: ['DTF por metro', 'DTF urgente', 'revision de archivo DTF'],
    relatedProducts: ['Camisetas', 'Sudaderas', 'Uniformes empresa'],
  },
  {
    id: 'rotulacion-commercial-core',
    label: 'Rotulacion comercial',
    primaryTerm: 'Rotulacion de furgonetas',
    variants: [
      'Rotulacion vehiculos empresa',
      'Rotulacion comercial',
      'Rotulacion integral',
      'Media rotulacion',
      'Rotulacion flotas comerciales',
    ],
    intents: ['commercial', 'transactional', 'local'],
    entity: 'rotulacion',
    stage: 'evaluate',
    priority: 'high',
    localities: ['barcelona', 'blanes', 'girona', 'costa-brava', 'cataluna'],
    relatedServices: ['Rotulacion comercial de furgonetas', 'Rotulacion integral de vehiculo', 'Escaparates'],
    relatedProducts: ['Vinilo comercial', 'Senaletica', 'Tarjetas empresa'],
  },
  {
    id: 'rotulacion-local-longtail',
    label: 'Rotulacion local',
    primaryTerm: 'Rotulacion furgonetas Barcelona',
    variants: [
      'Rotulacion vehiculos Blanes',
      'Vinilos comerciales Girona',
      'Rotulacion Costa Brava',
      'Rotulacion flotas Girona',
    ],
    intents: ['local', 'commercial'],
    entity: 'rotulacion',
    stage: 'evaluate',
    priority: 'high',
    localities: ['barcelona', 'blanes', 'girona', 'costa-brava'],
    relatedServices: ['Rotulacion comercial', 'Vehiculos de empresa', 'Flotas comerciales'],
    relatedProducts: ['Pegatinas empresa', 'Tarjetas empresa'],
  },
  {
    id: 'cards-business-core',
    label: 'Tarjetas de empresa',
    primaryTerm: 'tarjetas empresa',
    variants: ['tarjetas visita empresa', 'tarjetas personalizadas', 'tarjetas de visita Barcelona'],
    intents: ['transactional', 'commercial', 'local'],
    entity: 'tarjetas',
    stage: 'decide',
    priority: 'medium',
    localities: ['barcelona', 'girona', 'espana'],
    relatedServices: ['Tarjetas de visita', 'Papeleria corporativa'],
    relatedProducts: ['Flyers', 'Pegatinas', 'Sobres empresa'],
  },
  {
    id: 'flyers-commercial-core',
    label: 'Flyers personalizados',
    primaryTerm: 'flyers personalizados',
    variants: ['impresion flyers', 'flyers empresa', 'flyers Barcelona'],
    intents: ['transactional', 'commercial'],
    entity: 'flyers',
    stage: 'decide',
    priority: 'medium',
    localities: ['barcelona', 'blanes', 'girona', 'espana'],
    relatedServices: ['Flyers', 'Folletos plegados'],
    relatedProducts: ['Tarjetas empresa', 'Carteleria', 'Pegatinas'],
  },
  {
    id: 'stickers-custom-core',
    label: 'Pegatinas personalizadas',
    primaryTerm: 'pegatinas personalizadas',
    variants: ['pegatinas troqueladas', 'pegatinas empresa', 'adhesivos personalizados', 'pegatinas Barcelona'],
    intents: ['transactional', 'commercial', 'informational'],
    entity: 'pegatinas',
    stage: 'decide',
    priority: 'high',
    localities: ['barcelona', 'girona', 'espana'],
    relatedServices: ['Pegatinas troqueladas', 'Pegatinas en hoja', 'Vinilo comercial'],
    relatedProducts: ['Packaging', 'Tarjetas empresa', 'Escaparates'],
  },
  {
    id: 'vinyl-commercial-core',
    label: 'Vinilo comercial',
    primaryTerm: 'vinilos comerciales',
    variants: ['vinilo escaparate', 'vinilo para empresas', 'vinilo impreso', 'vinilos Girona'],
    intents: ['commercial', 'local', 'informational'],
    entity: 'vinilo-comercial',
    stage: 'evaluate',
    priority: 'high',
    localities: ['barcelona', 'blanes', 'girona', 'costa-brava'],
    relatedServices: ['Escaparates', 'Vinilo impreso', 'Senaletica'],
    relatedProducts: ['Rotulacion', 'Carteleria', 'Pegatinas'],
  },
  {
    id: 'large-format-core',
    label: 'Impresion gran formato',
    primaryTerm: 'impresion gran formato',
    variants: ['carteleria personalizada', 'lonas personalizadas', 'carteles empresa'],
    intents: ['commercial', 'transactional', 'informational'],
    entity: 'gran-formato',
    stage: 'evaluate',
    priority: 'medium',
    localities: ['barcelona', 'girona', 'espana'],
    relatedServices: ['Carteleria', 'Lonas', 'Senaletica'],
    relatedProducts: ['Vinilo comercial', 'Escaparates'],
  },
]
