import { relatedGuides } from '../articles/relatedGuides'
import { internalLinkGraph } from '../internal-links/internalLinkGraph'
import { relatedServicesByKey } from '../related/relatedServices'
import type { DiscoverabilityHub } from '../types/discoverability'

export const discoverabilityHubs: DiscoverabilityHub[] = [
  {
    id: 'dti',
    title: 'Hub DTI / DTF por metro',
    description: 'Entrada por demanda real de DTI y resolucion semantica hacia DTF por metro, archivo y soporte textil.',
    primaryKeywords: ['DTI por metro', 'DTF por metro', 'impresion DTF', 'DTF textil'],
    relatedServices: relatedServicesByKey.dtf,
    relatedProducts: [
      { id: 'hub-dtf-textil', title: 'Textil personalizado', description: 'Soportes finales para aplicar DTF y producir prendas.', href: '#/producto/textil', tag: 'Apparel' },
    ],
    relatedGuides: relatedGuides.filter((guide) => ['guide-dti-vs-dtf', 'guide-prepare-dti'].includes(guide.id)),
    localVariants: ['DTF Barcelona', 'DTF Blanes', 'DTF Girona', 'DTI Espana'],
    upsellRules: ['upsell-dtf'],
    internalLinks: internalLinkGraph.dtf,
  },
  {
    id: 'rotulacion',
    title: 'Hub de rotulacion comercial',
    description: 'Hub principal para vehiculos de empresa, flotas, escaparates y branding visible por ciudad.',
    primaryKeywords: ['Rotulacion comercial', 'Rotulacion de vehiculos empresa', 'Rotulacion integral'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [
      { id: 'hub-rot-cards', title: 'Tarjetas y papeleria', description: 'Soporte comercial complementario.', href: '#/producto/papeleria', tag: 'Branding' },
      { id: 'hub-rot-stickers', title: 'Pegatinas branding', description: 'Aplica la marca a packaging y punto de entrega.', href: '#/catalogo', tag: 'Sticker' },
    ],
    relatedGuides: relatedGuides.filter((guide) => ['guide-wrap-price', 'guide-wrap-ideas', 'guide-window-vinyl'].includes(guide.id)),
    localVariants: ['Rotulacion Barcelona', 'Rotulacion Blanes', 'Rotulacion Girona', 'Rotulacion Costa Brava'],
    upsellRules: ['upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'rotulacion-furgonetas',
    title: 'Hub de rotulacion de furgonetas',
    description: 'Subhub centrado en vehiculos comerciales, instalacion, cobertura parcial e integral.',
    primaryKeywords: ['Rotulacion de furgonetas', 'Media rotulacion', 'Rotulacion integral de vehiculo'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [],
    relatedGuides: relatedGuides.filter((guide) => ['guide-wrap-price', 'guide-wrap-ideas'].includes(guide.id)),
    localVariants: ['Rotulacion furgonetas Barcelona', 'Rotulacion furgonetas Blanes'],
    upsellRules: ['upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'textil-personalizado',
    title: 'Hub de textil personalizado',
    description: 'Nodo para prendas, uniformes y branding textil conectado a DTF y preparacion de archivo.',
    primaryKeywords: ['textil personalizado', 'uniformes empresa', 'camisetas personalizadas'],
    relatedServices: relatedServicesByKey.dtf,
    relatedProducts: [{ id: 'hub-textil-dtf', title: 'DTF por metro', description: 'Motor de produccion para textil y series cortas.', href: '#/producto/dtf', tag: 'DTF' }],
    relatedGuides: relatedGuides.filter((guide) => guide.id === 'guide-prepare-dti'),
    localVariants: ['textil personalizado Barcelona', 'uniformes empresa Girona'],
    upsellRules: ['upsell-dtf'],
    internalLinks: internalLinkGraph.dtf,
  },
  {
    id: 'pegatinas',
    title: 'Hub de pegatinas personalizadas',
    description: 'Nodo para adhesivos, branding, packaging y punto de venta.',
    primaryKeywords: ['pegatinas personalizadas', 'pegatinas troqueladas', 'adhesivos personalizados'],
    relatedServices: relatedServicesByKey.pegatinas,
    relatedProducts: [{ id: 'hub-sticker-print', title: 'Papeleria y tarjetas', description: 'Cruce comercial para negocios locales.', href: '#/producto/papeleria', tag: 'Cross-sell' }],
    relatedGuides: relatedGuides.filter((guide) => guide.id === 'guide-bleed-cutline'),
    localVariants: ['pegatinas Barcelona', 'pegatinas Girona'],
    upsellRules: ['upsell-tarjetas'],
    internalLinks: internalLinkGraph.catalogo,
  },
  {
    id: 'vinilo-impreso',
    title: 'Hub de vinilo impreso',
    description: 'Nodo para vinilo comercial, escaparates, senaletica y continuidad visual de marca.',
    primaryKeywords: ['vinilo impreso', 'vinilos comerciales', 'vinilo escaparate'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [{ id: 'hub-vinyl-rot', title: 'Rotulacion comercial', description: 'Lleva el vinilo a vehiculo, flota y retail.', href: '#/servicios/rotulacion', tag: 'Vehicle' }],
    relatedGuides: relatedGuides.filter((guide) => guide.id === 'guide-window-vinyl'),
    localVariants: ['vinilos comerciales Girona', 'vinilo escaparate Barcelona'],
    upsellRules: ['upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'tarjetas-papeleria',
    title: 'Hub de tarjetas y papeleria',
    description: 'Nodo para material comercial de empresa con salida hacia branding fisico y retail.',
    primaryKeywords: ['tarjetas empresa', 'tarjetas personalizadas', 'papeleria corporativa'],
    relatedServices: relatedServicesByKey.pegatinas,
    relatedProducts: [{ id: 'hub-paper-flyers', title: 'Flyers y folletos', description: 'Continua la conversacion comercial con material de reparto.', href: '#/producto/papeleria', tag: 'Print' }],
    relatedGuides: relatedGuides.filter((guide) => guide.id === 'guide-bleed-cutline'),
    localVariants: ['tarjetas empresa Barcelona', 'tarjetas visita Girona'],
    upsellRules: ['upsell-tarjetas'],
    internalLinks: internalLinkGraph.catalogo,
  },
  {
    id: 'empresas',
    title: 'Hub empresas',
    description: 'Agrupa rotulacion, textil, papeleria y branding para negocio local y equipos comerciales.',
    primaryKeywords: ['impresion para empresas', 'branding empresa', 'rotulacion vehiculos empresa'],
    relatedServices: [...relatedServicesByKey.rotulacion.slice(0, 3), ...relatedServicesByKey.dtf.slice(0, 2)],
    relatedProducts: [{ id: 'hub-company-catalog', title: 'Catalogo comercial', description: 'Entrada general a productos y servicios para empresa.', href: '#/catalogo', tag: 'Hub' }],
    relatedGuides: relatedGuides.filter((guide) => ['guide-wrap-ideas', 'guide-prepare-dti'].includes(guide.id)),
    localVariants: ['impresion para empresas Barcelona', 'branding local Blanes'],
    upsellRules: ['upsell-rotulacion-furgoneta', 'upsell-dtf', 'upsell-tarjetas'],
    internalLinks: internalLinkGraph.catalogo,
  },
  {
    id: 'barcelona',
    title: 'Hub local Barcelona',
    description: 'Servicios con intencion local alta para vehiculo, DTF y branding comercial en Barcelona.',
    primaryKeywords: ['Rotulacion Barcelona', 'DTF Barcelona', 'impresion personalizada Barcelona'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [],
    relatedGuides: relatedGuides.filter((guide) => ['guide-wrap-price', 'guide-prepare-dti'].includes(guide.id)),
    localVariants: ['Rotulacion furgonetas Barcelona', 'vinilos vehiculos Barcelona'],
    upsellRules: ['upsell-rotulacion-furgoneta', 'upsell-dtf'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'blanes',
    title: 'Hub local Blanes',
    description: 'Servicios de proximidad para negocios, rotulacion, escaparates y produccion impresa en Blanes.',
    primaryKeywords: ['Rotulacion Blanes', 'DTI Blanes', 'vinilos comerciales Blanes'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [],
    relatedGuides: relatedGuides.filter((guide) => guide.id === 'guide-wrap-ideas'),
    localVariants: ['Rotulacion vehiculos Blanes', 'DTF Blanes'],
    upsellRules: ['upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'girona-costa-brava',
    title: 'Hub local Girona / Costa Brava',
    description: 'Cobertura semantica para rotulacion, vinilo comercial y branding impreso en Girona y Costa Brava.',
    primaryKeywords: ['Rotulacion Girona', 'Rotulacion Costa Brava', 'vinilos empresas Girona'],
    relatedServices: relatedServicesByKey.rotulacion,
    relatedProducts: [],
    relatedGuides: relatedGuides.filter((guide) => ['guide-wrap-price', 'guide-window-vinyl'].includes(guide.id)),
    localVariants: ['flotas Girona', 'DTF Costa Brava'],
    upsellRules: ['upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.rotulacion,
  },
  {
    id: 'espana',
    title: 'Hub Espana',
    description: 'Capa nacional de captura semantica para DTI, rotulacion e impresion personalizada.',
    primaryKeywords: ['DTI Espana', 'Rotulacion vehiculos Espana', 'impresion personalizada Espana'],
    relatedServices: [...relatedServicesByKey.dtf.slice(0, 2), ...relatedServicesByKey.rotulacion.slice(0, 2)],
    relatedProducts: [],
    relatedGuides: relatedGuides.filter((guide) => ['guide-dti-vs-dtf', 'guide-bleed-cutline'].includes(guide.id)),
    localVariants: ['DTF Espana', 'Rotulacion Espana'],
    upsellRules: ['upsell-dtf', 'upsell-rotulacion-furgoneta'],
    internalLinks: internalLinkGraph.catalogo,
  },
]
