export type EditableZoneType = 'section' | 'data' | 'config' | 'page' | 'admin' | 'commerce' | 'motion'

export type EditableZone = {
  id: string
  label: string
  description: string
  filePath: string
  editableContentPath?: string
  type: EditableZoneType
}

export const siteMap: EditableZone[] = [
  {
    id: 'HOME_HERO',
    label: 'Hero principal de home',
    description: 'Secuencia fullscreen, titular principal, bullets y CTAs del primer impacto.',
    filePath: 'src/sections/home/HeroSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_METRICS',
    label: 'Metricas de home',
    description: 'Tarjetas de valor comercial y referencias rapidas del flujo principal.',
    filePath: 'src/sections/home/MetricsSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_FOUNDATION',
    label: 'Bloque base de home',
    description: 'Panel de lectura comercial y accesos rapidos del flujo principal.',
    filePath: 'src/sections/home/FoundationSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_PROCESS',
    label: 'Proceso de home',
    description: 'Cabecera y copy del bloque que explica el proceso de pedido.',
    filePath: 'src/sections/home/ProcessSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_EDITORIAL',
    label: 'Bloque editorial de home',
    description: 'Titulos de apoyo y conexiones con el contenido SEO del producto principal.',
    filePath: 'src/sections/home/EditorialSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_PREPARATION',
    label: 'Preparacion de home',
    description: 'Titulos de orientacion y confianza para preparar pedidos antes del checkout.',
    filePath: 'src/sections/home/PreparationSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_TRUST',
    label: 'Bloque de confianza de home',
    description: 'Cabecera del grid de confianza y mensaje comercial asociado.',
    filePath: 'src/sections/home/TrustSection.tsx',
    editableContentPath: 'src/content/homeContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_FAQ',
    label: 'Respuestas y FAQ de home',
    description: 'Titulos del bloque de objeciones y preguntas frecuentes.',
    filePath: 'src/sections/home/AnswersSection.tsx',
    editableContentPath: 'src/content/faqContent.ts',
    type: 'section',
  },
  {
    id: 'HOME_FINAL_CTA',
    label: 'CTA final de home',
    description: 'Bloque promocional final con copy y llamada principal.',
    filePath: 'src/sections/home/FinalCtaSection.tsx',
    editableContentPath: 'src/content/bannerContent.ts',
    type: 'section',
  },
  {
    id: 'CINEMATIC_SCROLL_SYSTEM',
    label: 'Sistema cinematografico de scroll',
    description: 'Capas decorativas, escenas GSAP + ScrollTrigger y placeholders de assets para la home.',
    filePath: 'src/motion/cinematic/CinematicHomeScroll.tsx',
    editableContentPath: 'src/motion/cinematic/cinematicScenes.ts',
    type: 'motion',
  },
  {
    id: 'NAV_MAIN',
    label: 'Navegacion principal',
    description: 'Marca, enlaces visibles y orden de la navegacion publica.',
    filePath: 'src/App.tsx',
    editableContentPath: 'src/content/navigationContent.ts',
    type: 'config',
  },
  {
    id: 'FOOTER_MAIN',
    label: 'Footer principal',
    description: 'Mensaje final y enlaces secundarios del pie publico.',
    filePath: 'src/App.tsx',
    editableContentPath: 'src/content/footerContent.ts',
    type: 'section',
  },
  {
    id: 'CATALOG_GRID',
    label: 'Grid principal de catalogo',
    description: 'Hero del catalogo, bloques introductorios y tarjetas de entrada.',
    filePath: 'src/pages/Catalogo.tsx',
    editableContentPath: 'src/content/catalogContent.ts',
    type: 'commerce',
  },
  {
    id: 'CATALOG_FILTERS',
    label: 'Categorias y lectura del catalogo',
    description: 'Etiquetas y descripciones de categorias visibles en catalogo.',
    filePath: 'src/catalog/categories.ts',
    editableContentPath: 'src/catalog/categories.ts',
    type: 'data',
  },
  {
    id: 'DTF_CONFIGURATOR',
    label: 'Configurador DTF',
    description: 'Campos, ayudas, presets, mensajes y textos del flujo DTF.',
    filePath: 'src/pages/DTFPage.tsx',
    editableContentPath: 'src/content/dtfContent.ts',
    type: 'commerce',
  },
  {
    id: 'ARTWORK_UPLOAD_FLOW',
    label: 'Flujo de artwork upload',
    description: 'Recorrido mock de subida, revisión, preview, recomendaciones y confirmación.',
    filePath: 'src/features/artwork-upload/components/ArtworkUploadFlow.tsx',
    editableContentPath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    type: 'commerce',
  },
  {
    id: 'ARTWORK_PREVIEW_CANVAS',
    label: 'Preview de impresión',
    description: 'Canvas/SVG mock con sangrado, corte, zona segura, orientación y escala.',
    filePath: 'src/features/artwork-upload/preview/PrintPreviewCanvas.tsx',
    editableContentPath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    type: 'commerce',
  },
  {
    id: 'ARTWORK_VALIDATION_RULES',
    label: 'Reglas de validación artwork',
    description: 'Checks mock de formato, peso, resolución, orientación, cutline y sangrado.',
    filePath: 'src/features/artwork-upload/validation/validateArtworkFile.ts',
    editableContentPath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    type: 'config',
  },
  {
    id: 'ARTWORK_PRODUCT_GUIDES',
    label: 'Guías por producto',
    description: 'Sangrado, zona segura, orientación y overlays según producto impreso.',
    filePath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    editableContentPath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    type: 'config',
  },
  {
    id: 'ARTWORK_RECOMMENDATIONS',
    label: 'Recomendaciones de corrección',
    description: 'Mensajes mock inteligentes para corregir o validar el archivo antes de producir.',
    filePath: 'src/features/artwork-upload/validation/validateArtworkFile.ts',
    editableContentPath: 'src/features/artwork-upload/product-rules/artworkProductRules.ts',
    type: 'commerce',
  },
  {
    id: 'PREPRESS_CHECKS',
    label: 'Checks avanzados de preprensa',
    description: 'Preflight mock con formato, DPI, cutline, color, sangrado, capas y escala por producto.',
    filePath: 'src/features/prepress/checks/buildPrepressChecks.ts',
    editableContentPath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    type: 'config',
  },
  {
    id: 'PREPRESS_SCORE',
    label: 'Score de readiness de impresion',
    description: 'Score 0-100, estado global y prioridad de correccion antes de producir.',
    filePath: 'src/features/prepress/scoring/scorePrepressChecks.ts',
    editableContentPath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    type: 'commerce',
  },
  {
    id: 'PREPRESS_RECOMMENDATIONS',
    label: 'Recomendaciones de preprensa',
    description: 'Mensajes accionables para cliente y taller segun el analisis tecnico mock.',
    filePath: 'src/features/prepress/recommendations/buildPrepressRecommendations.ts',
    editableContentPath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    type: 'commerce',
  },
  {
    id: 'PREPRESS_ADMIN_REVIEW',
    label: 'Revision tecnica admin',
    description: 'Panel tecnico completo para uploads y detalle de pedido con score, impactos y checks.',
    filePath: 'src/features/prepress/components/PrepressAdminReviewPanel.tsx',
    editableContentPath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    type: 'admin',
  },
  {
    id: 'PREPRESS_PRODUCT_RULESETS',
    label: 'Rulesets tecnicos por producto',
    description: 'Checks requeridos, umbrales y copy amigable por familia de producto.',
    filePath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    editableContentPath: 'src/features/prepress/rules/productPrepressRulesets.ts',
    type: 'config',
  },
  {
    id: 'PRINT_TEMPLATE_DOWNLOADS',
    label: 'Descarga de plantillas',
    description: 'CTA y cards de descarga mock para plantillas tecnicas por producto.',
    filePath: 'src/features/print-templates/components/ProductTemplateDownloads.tsx',
    editableContentPath: 'src/infrastructure/storage/mock/mockProductTemplateRepository.ts',
    type: 'commerce',
  },
  {
    id: 'PRINT_TEMPLATE_GUIDES',
    label: 'Guias de plantilla',
    description: 'Sangrado, corte, zona segura y notas tecnicas ligadas a cada plantilla.',
    filePath: 'src/features/print-templates/components/TemplateGuidePanel.tsx',
    editableContentPath: 'src/infrastructure/storage/mock/mockProductTemplateRepository.ts',
    type: 'config',
  },
  {
    id: 'PRINT_TEMPLATE_CATALOG',
    label: 'Catalogo de plantillas',
    description: 'Inventario mock de plantillas por producto, formato y version.',
    filePath: 'src/infrastructure/storage/mock/mockProductTemplateRepository.ts',
    editableContentPath: 'src/infrastructure/storage/mock/mockProductTemplateRepository.ts',
    type: 'data',
  },
  {
    id: 'PRINT_TEMPLATE_FORMATS',
    label: 'Selector de formatos de plantilla',
    description: 'Formatos disponibles, recomendado y fallback de descarga por plantilla.',
    filePath: 'src/features/print-templates/components/TemplateFormatSelector.tsx',
    editableContentPath: 'src/infrastructure/storage/mock/mockProductTemplateRepository.ts',
    type: 'config',
  },
  {
    id: 'REPORTING_CENTER',
    label: 'Centro de reporting',
    description: 'Vista central de reportes mock, exportacion y historial operativo.',
    filePath: 'src/admin/pages/ReportingPage.tsx',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'REPORT_EXPORTS',
    label: 'Exportadores de reportes',
    description: 'Selector de formato, export JSON/CSV y vista imprimible mock.',
    filePath: 'src/features/reporting/components/ReportPreviewPanel.tsx',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'commerce',
  },
  {
    id: 'REPORT_ORDER_SUMMARY',
    label: 'Reporte resumen de pedido',
    description: 'Documento mock con cliente, produccion, importes y entrega del pedido.',
    filePath: 'src/features/reporting/services/reportingService.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'commerce',
  },
  {
    id: 'REPORT_PRODUCTION_SHEET',
    label: 'Hoja de produccion',
    description: 'Documento mock de cola productiva, slot, maquina y notas de taller.',
    filePath: 'src/features/reporting/services/reportingService.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'REPORT_PREPRESS_CHECKS',
    label: 'Reporte de checks de preprensa',
    description: 'Resumen exportable del score, checks y recomendaciones tecnicas del artwork.',
    filePath: 'src/features/reporting/services/reportingService.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'REPORT_ADMIN_KPIS',
    label: 'Reporte KPI admin',
    description: 'Snapshot ejecutivo mock con KPIs operativos, service, dispatch y capacidad.',
    filePath: 'src/features/reporting/services/reportingService.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'DOCUMENT_LAYOUTS',
    label: 'Layouts documentales',
    description: 'Layouts reutilizables para print view, futura exportacion PDF y documentos operativos.',
    filePath: 'src/features/documents/layouts/OperationalDocumentLayout.tsx',
    editableContentPath: 'src/features/documents/mock/documentDefinitions.ts',
    type: 'config',
  },
  {
    id: 'DOCUMENT_PRINT_STYLES',
    label: 'Estilos print-safe',
    description: 'Tipografia, A4, page breaks y ocultacion de chrome visual para documentos imprimibles.',
    filePath: 'src/App.css',
    editableContentPath: 'src/App.css',
    type: 'config',
  },
  {
    id: 'DOCUMENT_ORDER_SUMMARY',
    label: 'Documento de resumen de pedido',
    description: 'Mapper y layout del documento operativo de pedido antes del PDF real.',
    filePath: 'src/features/documents/services/documentMapper.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'commerce',
  },
  {
    id: 'DOCUMENT_PRODUCTION_SHEET',
    label: 'Documento de hoja de produccion',
    description: 'Contrato visual para cola de taller, maquina, slot y checklist.',
    filePath: 'src/features/documents/services/documentMapper.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'DOCUMENT_PREPRESS_REPORT',
    label: 'Documento de preprensa',
    description: 'Contrato visual para score, checks y recomendaciones tecnicas.',
    filePath: 'src/features/documents/services/documentMapper.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'DOCUMENT_DELIVERY_HANDOFF',
    label: 'Documento de handoff y entrega',
    description: 'Contrato visual para packing, tracking, ventana y firma mock.',
    filePath: 'src/features/documents/services/documentMapper.ts',
    editableContentPath: 'src/features/reporting/mock/reportDefinitions.ts',
    type: 'admin',
  },
  {
    id: 'SEO_INTENT',
    label: 'Motor de intencion de busqueda',
    description: 'Grupos de keywords priorizados por intencion, entidad y etapa comercial.',
    filePath: 'src/features/search-intelligence/keywords/keywordGroups.ts',
    editableContentPath: 'src/features/search-intelligence/keywords/keywordGroups.ts',
    type: 'config',
  },
  {
    id: 'SEO_CLUSTERS',
    label: 'Clusters y hubs topicos',
    description: 'Mapa de hubs, supporting pages y enlazado interno por entidad de negocio.',
    filePath: 'src/features/search-intelligence/clusters/topicalClusters.ts',
    editableContentPath: 'src/features/search-intelligence/clusters/topicalClusters.ts',
    type: 'config',
  },
  {
    id: 'SEO_LOCAL_QUESTIONS',
    label: 'Preguntas locales y answer-style',
    description: 'FAQ orientadas a busqueda conversacional, local y de preparacion de compra.',
    filePath: 'src/features/search-intelligence/questions/answerStyleQuestions.ts',
    editableContentPath: 'src/features/search-intelligence/questions/answerStyleQuestions.ts',
    type: 'config',
  },
  {
    id: 'SEO_ENTITY_MAP',
    label: 'Mapa de entidades SEO',
    description: 'Relaciones entre servicios, productos, branding y preguntas relacionadas.',
    filePath: 'src/features/search-intelligence/entities/entityRelationshipMap.ts',
    editableContentPath: 'src/features/search-intelligence/entities/entityRelationshipMap.ts',
    type: 'data',
  },
  {
    id: 'SEO_LONGTAIL',
    label: 'Long-tail local y comercial',
    description: 'Cobertura por ciudad, territorio, oportunidad semantica y necesidades locales.',
    filePath: 'src/features/search-intelligence/local/localSearchMap.ts',
    editableContentPath: 'src/features/search-intelligence/local/localSearchMap.ts',
    type: 'data',
  },
  {
    id: 'SEO_RELATED_PRODUCTS',
    label: 'Relacion entre servicios y productos',
    description: 'Conexiones internas entre rotulacion, DTF, branding, papeleria y soportes relacionados.',
    filePath: 'src/features/search-intelligence/entities/entityRelationshipMap.ts',
    editableContentPath: 'src/features/search-intelligence/entities/entityRelationshipMap.ts',
    type: 'config',
  },
  {
    id: 'PRODUCT_DETAIL',
    label: 'Sistema de detalle de producto',
    description: 'Plantilla premium reutilizable de producto configurable, storytelling y CTA final.',
    filePath: 'src/features/products/product-detail/ProductExperiencePage.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'commerce',
  },
  {
    id: 'PRODUCT_HERO',
    label: 'Hero de producto',
    description: 'Eyebrow, titular, intro y sticker words de la cabecera editorial.',
    filePath: 'src/features/products/product-detail/sections/ProductHeroSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'section',
  },
  {
    id: 'PRODUCT_GALLERY',
    label: 'Galeria de producto',
    description: 'Frames, placeholders visuales y narrativa de galeria premium.',
    filePath: 'src/features/products/product-detail/sections/ProductGallerySection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'section',
  },
  {
    id: 'PRODUCT_CONFIGURATOR',
    label: 'Configurador de producto',
    description: 'Campos, CTA y soporte operativo del configurador reutilizable.',
    filePath: 'src/features/products/product-detail/sections/ProductConfiguratorSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'commerce',
  },
  {
    id: 'PRODUCT_SPECS',
    label: 'Specs de producto',
    description: 'Tarjetas de modo de compra, precio y archivo para lectura rápida.',
    filePath: 'src/features/products/product-detail/sections/ProductSpecsSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'section',
  },
  {
    id: 'PRODUCT_STORY',
    label: 'Storytelling de producto',
    description: 'Bloques editoriales, highlights y narrativa comercial del producto.',
    filePath: 'src/features/products/product-detail/sections/ProductStorySection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'section',
  },
  {
    id: 'PRODUCT_RECOMMENDATIONS',
    label: 'Recomendaciones de producto',
    description: 'Cross-sell premium y siguientes pasos contextuales por producto.',
    filePath: 'src/features/products/product-detail/sections/ProductRecommendationsSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'commerce',
  },
  {
    id: 'PRODUCT_FAQ',
    label: 'FAQ y confianza de producto',
    description: 'SEO, guías de archivo, objeciones y preguntas frecuentes del detalle.',
    filePath: 'src/features/products/product-detail/sections/ProductFaqSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'section',
  },
  {
    id: 'PRODUCT_FINAL_CTA',
    label: 'CTA final de producto',
    description: 'Bloque final de cierre, salto a carrito o propuesta.',
    filePath: 'src/features/products/product-detail/sections/ProductFinalCtaSection.tsx',
    editableContentPath: 'src/features/products/product-detail/data/productExperienceContent.ts',
    type: 'commerce',
  },
  {
    id: 'CART_DRAWER',
    label: 'Carrito y resumen',
    description: 'Textos del resumen, CTAs de carrito y mensajes de continuidad comercial.',
    filePath: 'src/pages/Carrito.tsx',
    editableContentPath: 'src/content/pricingContent.ts',
    type: 'commerce',
  },
  {
    id: 'CHECKOUT_MOCK_FLOW',
    label: 'Flujo de checkout mock',
    description: 'Revision, envio, pago mock y confirmacion del pedido local.',
    filePath: 'src/pages/Checkout.tsx',
    editableContentPath: 'src/content/pricingContent.ts',
    type: 'commerce',
  },
  {
    id: 'CART_RECOMMENDATIONS',
    label: 'Recomendaciones y cross-sell del carrito',
    description: 'Bloques premium sugeridos en carrito y continuidad comercial.',
    filePath: 'src/features/cart/data/cartRecommendations.ts',
    editableContentPath: 'src/features/cart/data/cartRecommendations.ts',
    type: 'commerce',
  },
  {
    id: 'ORDER_LIFECYCLE_MOCK',
    label: 'Lifecycle mock de pedidos',
    description: 'Timeline local de seguimiento para checkout y cuenta cliente.',
    filePath: 'src/features/orders/utils/orderLifecycle.ts',
    editableContentPath: 'src/features/orders/utils/orderLifecycle.ts',
    type: 'commerce',
  },
  {
    id: 'ADMIN_DASHBOARD',
    label: 'Dashboard admin mock',
    description: 'Mensajes y acciones rapidas del panel interno preparado.',
    filePath: 'src/admin/pages/DashboardPage.tsx',
    editableContentPath: 'src/content/adminMockContent.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_OPERATIONS_DASHBOARD',
    label: 'Dashboard operativo interno',
    description: 'KPIs, activity feed, urgentes y colas visibles del sistema de operaciones mock.',
    filePath: 'src/admin/pages/DashboardPage.tsx',
    editableContentPath: 'src/features/operations/mock/operationsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_CAPACITY_DASHBOARD',
    label: 'Capacidad diaria del admin',
    description: 'Capacidad de hoy, entregas proximas, carga por operador y alertas de sobrecarga.',
    filePath: 'src/admin/pages/DashboardPage.tsx',
    editableContentPath: 'src/features/operations/capacity/capacityMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_OPERATOR_WORKLOAD',
    label: 'Carga por operador',
    description: 'Horas usadas, hueco restante y reparto de urgentes por operador mock.',
    filePath: 'src/features/operations/capacity/CapacityDashboardWidgets.tsx',
    editableContentPath: 'src/features/operations/capacity/capacityMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_CONTENT_STUDIO',
    label: 'CMS interno mock',
    description: 'Studio local para simular edicion por zonas sin persistencia externa.',
    filePath: 'src/admin/pages/ContentStudioPage.tsx',
    editableContentPath: 'src/config/siteMap.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ACCOUNTS',
    label: 'Cuentas internas mock',
    description: 'Usuarios internos, ownership y carga resumida antes de auth real.',
    filePath: 'src/admin/pages/AccountsPage.tsx',
    editableContentPath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ROLES',
    label: 'Roles operativos mock',
    description: 'Definiciones visuales de roles y alcance operativo por area.',
    filePath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    editableContentPath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_PERMISSIONS',
    label: 'Permisos mock',
    description: 'Lista de permisos visuales preparada para futura ACL real.',
    filePath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    editableContentPath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_APPROVAL_CHAINS',
    label: 'Cadenas de aprobacion mock',
    description: 'Workflows de artwork, incidencias, cambios urgentes y content publish.',
    filePath: 'src/features/admin-accounts/approval-chains/approvalChainService.ts',
    editableContentPath: 'src/features/admin-accounts/mock/adminAccountsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_AUDIT_TRAIL',
    label: 'Audit trail administrativo',
    description: 'Timeline mock de ownership, cambios de estado y acciones internas.',
    filePath: 'src/features/admin-accounts/audit/auditTrailService.ts',
    editableContentPath: 'src/admin/store/useAdminUiStore.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_CLIENT_SERVICE',
    label: 'Mesa de client service',
    description: 'Tickets, approvals, SLA, escalados y mensajes mock del panel interno.',
    filePath: 'src/admin/pages/ClientServicePage.tsx',
    editableContentPath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_SLA_MONITOR',
    label: 'Monitor SLA interno',
    description: 'Lectura de casos en riesgo, breached y recomendaciones de escalado.',
    filePath: 'src/features/operations/client-service/sla/slaSelectors.ts',
    editableContentPath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ARTWORK_APPROVALS',
    label: 'Flujo de approvals de artwork',
    description: 'Estados de revision, cambios solicitados y bloqueo para produccion.',
    filePath: 'src/features/operations/client-service/approvals/approvalFlow.ts',
    editableContentPath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_RESPONSE_TEMPLATES',
    label: 'Templates de respuesta',
    description: 'Mensajes mock premium para approval, incidencias y seguimiento al cliente.',
    filePath: 'src/features/operations/client-service/templates/responseTemplates.ts',
    editableContentPath: 'src/features/operations/client-service/templates/responseTemplates.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_CUSTOMER_ISSUES',
    label: 'Incidencias de cliente',
    description: 'Tipos de incidencia, severidad y timeline de casos internos.',
    filePath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    editableContentPath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ESCALATION_PANEL',
    label: 'Panel de escalado',
    description: 'Reglas y recomendaciones mock para elevar casos por SLA o impacto.',
    filePath: 'src/features/operations/client-service/escalation/escalationRules.ts',
    editableContentPath: 'src/features/operations/client-service/mock/clientServiceMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ORDERS',
    label: 'Pedidos admin mock',
    description: 'Overrides y contenido mock de pedidos internos.',
    filePath: 'src/content/adminMockContent.ts',
    editableContentPath: 'src/content/adminMockContent.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_CUSTOMERS',
    label: 'Clientes admin mock',
    description: 'Contenido de apoyo y referencias mock del panel de clientes.',
    filePath: 'src/content/adminMockContent.ts',
    editableContentPath: 'src/content/adminMockContent.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_UPLOADS',
    label: 'Uploads admin mock',
    description: 'Notas de revision y estados mock para archivos.',
    filePath: 'src/content/adminMockContent.ts',
    editableContentPath: 'src/content/adminMockContent.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_PRODUCTION_PIPELINE',
    label: 'Pipeline de produccion interno',
    description: 'Etapas mock de produccion, resumen por fase y cola operativa.',
    filePath: 'src/admin/pages/ProductionPage.tsx',
    editableContentPath: 'src/features/operations/mock/operationsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_SCHEDULING_BOARD',
    label: 'Board de planificacion semanal',
    description: 'Vista semanal mock con entregas, slots por dia y conflictos operativos.',
    filePath: 'src/admin/pages/ProductionPage.tsx',
    editableContentPath: 'src/features/operations/scheduling/schedulingService.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_MACHINE_SLOTS',
    label: 'Slots de maquina',
    description: 'Capacidad mock por maquina y ventana de produccion.',
    filePath: 'src/features/operations/scheduling/SchedulingBoard.tsx',
    editableContentPath: 'src/features/operations/capacity/capacityMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_DISPATCH_DASHBOARD',
    label: 'Dashboard de despacho',
    description: 'Widgets mock de salida, packing, handoff e incidencias de entrega.',
    filePath: 'src/admin/pages/DashboardPage.tsx',
    editableContentPath: 'src/features/operations/dispatch/dispatchMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_DELIVERY_BOARD',
    label: 'Board de entrega',
    description: 'Columnas mock de packing, pickup, delivery queue e incidencias.',
    filePath: 'src/admin/pages/ProductionPage.tsx',
    editableContentPath: 'src/features/operations/delivery/deliveryMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_PICKUP_QUEUE',
    label: 'Cola de recogidas',
    description: 'Pedidos preparados para pickup y handoff local.',
    filePath: 'src/features/operations/delivery/DispatchBoard.tsx',
    editableContentPath: 'src/features/operations/dispatch/dispatchMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ORDER_DETAIL',
    label: 'Detalle operativo de pedido',
    description: 'Timeline, notas, pipeline y cambios de estado del pedido interno.',
    filePath: 'src/admin/pages/OrderDetailPage.tsx',
    editableContentPath: 'src/features/operations/mock/operationsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_UPLOAD_REVIEW',
    label: 'Revision interna de uploads',
    description: 'Artwork cards, metadata mock, validacion y notas de revision.',
    filePath: 'src/admin/pages/UploadsPage.tsx',
    editableContentPath: 'src/features/operations/mock/operationsMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_INTERNAL_NOTES',
    label: 'Notas internas operativas',
    description: 'Comentarios QA, produccion e internos con persistencia mock/local.',
    filePath: 'src/admin/pages/OrderDetailPage.tsx',
    editableContentPath: 'src/admin/store/useAdminUiStore.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_DELIVERY_MESSAGES',
    label: 'Mensajes mock de entrega',
    description: 'Previews locales de pickup, envio, retraso, incidencia y entrega completada.',
    filePath: 'src/admin/pages/OrderDetailPage.tsx',
    editableContentPath: 'src/features/operations/dispatch/dispatchMockData.ts',
    type: 'admin',
  },
  {
    id: 'ADMIN_ORDER_HANDOFF',
    label: 'Handoff del pedido',
    description: 'Tracking mock, carrier, ventana y timeline de salida del pedido interno.',
    filePath: 'src/admin/pages/OrderDetailPage.tsx',
    editableContentPath: 'src/admin/store/useAdminUiStore.ts',
    type: 'admin',
  },
]

export const siteMapById = Object.fromEntries(siteMap.map((zone) => [zone.id, zone]))
