import type { CinematicAssetDefinition, CinematicAssetKey } from './cinematic.types'

export const cinematicAssets: Record<CinematicAssetKey, CinematicAssetDefinition> = {
  textileHoodieTransparent: {
    key: 'textileHoodieTransparent',
    label: 'Sudadera/camiseta textil sin fondo',
    expectedPath: '/assets/cinematic/textile-hoodie-transparent.webp',
    available: false,
    recommendedFormat: 'webp',
    transparentBackground: true,
    orientation: 'portrait',
    recommendedSize: '2400x3000',
    notes: 'Prenda protagonista para transicion textil/DTF, con volumen y costuras visibles.',
    priority: 'high',
  },
  dtfRollTransparent: {
    key: 'dtfRollTransparent',
    label: 'Rollo DTF sin fondo',
    expectedPath: '/assets/cinematic/dtf-roll-transparent.webp',
    available: false,
    recommendedFormat: 'webp',
    transparentBackground: true,
    orientation: 'landscape',
    recommendedSize: '2600x1600',
    notes: 'Detalle de material DTF o bobina para reforzar continuidad del flujo de produccion.',
    priority: 'medium',
  },
  vehicleWrapCarTransparent: {
    key: 'vehicleWrapCarTransparent',
    label: 'Vehiculo wrapping sin fondo',
    expectedPath: '/assets/cinematic/wrap-car-transparent.webp',
    available: false,
    recommendedFormat: 'webp',
    transparentBackground: true,
    orientation: 'landscape',
    recommendedSize: '3200x1800',
    notes: 'Vehiculo lateral o tres cuartos, pensado para transicion de rotulacion/wrapping.',
    priority: 'high',
  },
  printMachineDetail: {
    key: 'printMachineDetail',
    label: 'Detalle de maquina/produccion',
    expectedPath: '/assets/cinematic/print-detail-transparent.webp',
    available: false,
    recommendedFormat: 'webp',
    transparentBackground: true,
    orientation: 'landscape',
    recommendedSize: '2600x1600',
    notes: 'Plano de maquina, tinta o manos de produccion para escena de detalle tecnico.',
    priority: 'medium',
  },
  finalBrandObject: {
    key: 'finalBrandObject',
    label: 'Objeto de cierre de marca',
    expectedPath: '/assets/cinematic/final-brand-object.webp',
    available: false,
    recommendedFormat: 'webp',
    transparentBackground: true,
    orientation: 'square',
    recommendedSize: '2200x2200',
    notes: 'Elemento de cierre premium para el reveal final antes del CTA.',
    priority: 'high',
  },
}

export const cinematicAssetList = Object.values(cinematicAssets)
