import type { CinematicSceneDefinition } from './cinematic.types'

export const cinematicScenes: CinematicSceneDefinition[] = [
  {
    id: 'HERO_CINEMATIC',
    label: 'Hero cinematico',
    description: 'Profundidad suave y glow editorial sobre la secuencia principal sin tapar el contenido.',
    triggerZoneId: 'HOME_HERO',
    assetKey: 'dtfRollTransparent',
    className: 'scene-hero-cinematic',
    accent: 'rgba(240, 20, 216, 0.22)',
    depth: 0.12,
  },
  {
    id: 'TEXTILE_DTF_TRANSITION',
    label: 'Transicion textil y DTF',
    description: 'Placeholder para sudadera/camiseta y volumen textil despues del hero.',
    triggerZoneId: 'HOME_FOUNDATION',
    assetKey: 'textileHoodieTransparent',
    className: 'scene-textile-dtf',
    accent: 'rgba(217, 255, 0, 0.18)',
    depth: 0.16,
  },
  {
    id: 'VEHICLE_WRAP_TRANSITION',
    label: 'Transicion rotulacion vehiculo',
    description: 'Placeholder horizontal para coche o volumen de wrapping sobre el bloque de proceso.',
    triggerZoneId: 'HOME_PROCESS',
    assetKey: 'vehicleWrapCarTransparent',
    className: 'scene-vehicle-wrap',
    accent: 'rgba(217, 255, 0, 0.18)',
    depth: 0.18,
  },
  {
    id: 'PRODUCTION_DETAIL_TRANSITION',
    label: 'Transicion detalle de produccion',
    description: 'Placeholder para maquina, tinta, manos y detalle tecnico sobre la parte editorial.',
    triggerZoneId: 'HOME_EDITORIAL',
    assetKey: 'printMachineDetail',
    className: 'scene-production-detail',
    accent: 'rgba(26, 217, 226, 0.16)',
    depth: 0.14,
  },
  {
    id: 'FINAL_BRAND_REVEAL',
    label: 'Reveal final de marca',
    description: 'Cierre limpio y elegante antes del CTA final.',
    triggerZoneId: 'HOME_FINAL_CTA',
    assetKey: 'finalBrandObject',
    className: 'scene-final-brand',
    accent: 'rgba(240, 20, 216, 0.18)',
    depth: 0.1,
  },
]
