import type { Customer, Order } from '../types/backend'

const mockCustomerTimestamp = '2026-04-01T09:00:00.000Z'

export const mockCustomer: Customer = {
  id: 'customer-demo',
  name: 'Studio Norte Textil',
  email: 'compras@studionorte.es',
  phone: '+34 600 123 456',
  company: 'Studio Norte Textil',
  createdAt: mockCustomerTimestamp,
  updatedAt: mockCustomerTimestamp,
}

export const mockOrders: Order[] = [
  {
    id: 'RP-24031',
    customerId: mockCustomer.id,
    customer: mockCustomer,
    createdAt: '2026-04-22T10:00:00.000Z',
    paymentStatus: 'disabled',
    source: 'mock_frontend',
    status: 'pending_review',
    total: 68.3,
    items: [
      {
        id: 'item-rp24031-dtf',
        productType: 'dtf',
        productName: 'DTF por metro',
        configuration: {
          meters: 4.2,
          quality: 'premium',
          urgency: 'express',
          notes: 'Frontal camisetas drop mayo.',
        },
        pricing: {
          unitPrice: 14.5,
          subtotal: 60.3,
          extras: 8,
          total: 68.3,
        },
        artwork: {
          id: 'upload-rp24031',
          itemId: 'item-rp24031-dtf',
          orderId: 'RP-24031',
          fileName: 'rp24031-frontal-camisetas.pdf',
          fileType: 'application/pdf',
          fileSize: 2480000,
          formatLabel: 'PDF',
          status: 'pending_review',
          uploadedAt: '2026-04-22T10:00:00.000Z',
          notes: 'Archivo principal asociado al pedido demo para revision y aprobacion tecnica.',
        },
      },
    ],
  },
  {
    id: 'RP-24018',
    customerId: mockCustomer.id,
    customer: mockCustomer,
    createdAt: '2026-04-18T09:00:00.000Z',
    paymentStatus: 'pending',
    source: 'mock_frontend',
    status: 'approved',
    total: 245,
    items: [
      {
        id: 'item-rp24018-lona',
        productType: 'dtf',
        productName: 'Lonas publicitarias',
        configuration: {
          meters: 1,
          quality: 'standard',
          urgency: 'normal',
          notes: 'Pedido mock de gran formato.',
        },
        pricing: {
          unitPrice: 245,
          subtotal: 245,
          extras: 0,
          total: 245,
        },
        artwork: {
          id: 'upload-rp24018',
          itemId: 'item-rp24018-lona',
          orderId: 'RP-24018',
          fileName: 'lonas-feria-principal.pdf',
          fileType: 'application/pdf',
          fileSize: 3210000,
          formatLabel: 'PDF',
          status: 'approved',
          uploadedAt: '2026-04-18T09:00:00.000Z',
        },
      },
    ],
  },
  {
    id: 'RP-23994',
    customerId: mockCustomer.id,
    customer: mockCustomer,
    createdAt: '2026-04-11T09:00:00.000Z',
    paymentStatus: 'pending',
    source: 'mock_frontend',
    status: 'in_production',
    total: 182.5,
    items: [
      {
        id: 'item-rp23994-textil',
        productType: 'dtf',
        productName: 'Textil personalizado',
        configuration: {
          meters: 1,
          quality: 'standard',
          urgency: 'normal',
          notes: 'Pedido mock textil.',
        },
        pricing: {
          unitPrice: 182.5,
          subtotal: 182.5,
          extras: 0,
          total: 182.5,
        },
        artwork: {
          id: 'upload-rp23994',
          itemId: 'item-rp23994-textil',
          orderId: 'RP-23994',
          fileName: 'drop-mayo-espalda.png',
          fileType: 'image/png',
          fileSize: 1840000,
          formatLabel: 'PNG',
          status: 'in_production',
          uploadedAt: '2026-04-11T09:00:00.000Z',
        },
      },
    ],
  },
  {
    id: 'RP-23970',
    customerId: mockCustomer.id,
    customer: mockCustomer,
    createdAt: '2026-04-04T09:00:00.000Z',
    paymentStatus: 'pending',
    source: 'mock_frontend',
    status: 'ready',
    total: 540,
    items: [
      {
        id: 'item-rp23970-rotulacion',
        productType: 'dtf',
        productName: 'Rotulacion de vehiculos',
        configuration: {
          meters: 1,
          quality: 'standard',
          urgency: 'normal',
          notes: 'Pedido mock rotulacion.',
        },
        pricing: {
          unitPrice: 540,
          subtotal: 540,
          extras: 0,
          total: 540,
        },
        artwork: {
          id: 'upload-rp23970',
          itemId: 'item-rp23970-rotulacion',
          orderId: 'RP-23970',
          fileName: 'vehiculo-flota-lateral.ai',
          fileType: 'application/postscript',
          fileSize: 4120000,
          formatLabel: 'AI',
          status: 'ready',
          uploadedAt: '2026-04-04T09:00:00.000Z',
        },
      },
    ],
  },
  {
    id: 'RP-23921',
    customerId: mockCustomer.id,
    customer: mockCustomer,
    createdAt: '2026-03-27T09:00:00.000Z',
    paymentStatus: 'paid',
    source: 'mock_frontend',
    status: 'completed',
    total: 96,
    items: [
      {
        id: 'item-rp23921-stickers',
        productType: 'dtf',
        productName: 'Pegatinas personalizadas',
        configuration: {
          meters: 1,
          quality: 'standard',
          urgency: 'normal',
          notes: 'Pedido mock stickers.',
        },
        pricing: {
          unitPrice: 96,
          subtotal: 96,
          extras: 0,
          total: 96,
        },
        artwork: {
          id: 'upload-rp23921',
          itemId: 'item-rp23921-stickers',
          orderId: 'RP-23921',
          fileName: 'sticker-pack-marca.svg',
          fileType: 'image/svg+xml',
          fileSize: 128000,
          formatLabel: 'SVG',
          status: 'completed',
          uploadedAt: '2026-03-27T09:00:00.000Z',
        },
      },
    ],
  },
]
