import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const vehicleSizeField: ConfiguratorField = {
  key: 'size',
  type: 'size',
  label: 'Tamano de vehiculo',
  required: true,
  options: [
    { value: 'S', label: 'S' },
    { value: 'M', label: 'M' },
    { value: 'L', label: 'L' },
    { value: 'XL', label: 'XL' },
  ],
}

const serviceField: ConfiguratorField = { key: 'variant', type: 'variant', label: 'Servicio', required: true, options: [] }

export const rotulacionEntries: CatalogEntry[] = [
  {
    id: 'rotulacion-basica',
    slug: 'rotulacion-basica-furgoneta',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion de furgonetas',
    description: 'Logo, datos de contacto y grafica comercial para furgonetas de empresa. Incluye material e instalacion. No incluye diseno.',
    shortDescription: 'Base comercial para vehiculos de empresa y marcas que quieren verse mejor en calle.',
    route: '#/producto/rotulacion-furgonetas',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 180, max: 1000 },
    badge: 'Presupuesto',
    notes: ['Vinilo en color plano o impreso.'],
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-parcial',
    slug: 'rotulacion-parcial-furgoneta',
    kind: 'service',
    category: 'rotulacion',
    name: 'Media rotulacion',
    description: 'Aplicacion por secciones sobre laterales, trasera o zonas clave. Util para vehiculos particulares y flotas comerciales.',
    shortDescription: 'Cobertura parcial para negocios que quieren impacto visual sin ir a un wrap completo.',
    route: '#/producto/rotulacion-furgonetas',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 300, max: 1000 },
    badge: 'Presupuesto',
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-semi',
    slug: 'rotulacion-semi-integral',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion comercial ampliada',
    description: 'Laterales, trasera y zonas extendidas con lectura visual de marca y homologacion segun proyecto.',
    shortDescription: 'Cobertura amplia para vehiculos de empresa y proyectos con presencia comercial fuerte.',
    route: '#/producto/rotulacion-furgonetas',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 900, max: 2000 },
    badge: 'Presupuesto',
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-full-wrap',
    slug: 'rotulacion-full-wrap',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion integral',
    description: 'Cobertura completa para vehiculos de empresa, flotas comerciales o proyectos de branding total. Incluye material e instalacion. No incluye diseno.',
    shortDescription: 'Wrap integral con propuesta previa obligatoria y enfoque premium.',
    route: '#/producto/rotulacion-furgonetas',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 1800, max: 3400 },
    badge: 'Presupuesto',
    notes: ['Duracion aproximada de 3 a 5 anos.'],
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
]
