import { commonArtworkFormats } from '../configurators/commonArtworkFormats'
import { defaultCommercialNoticeKeys } from '../notices/legalNotices'
import type { CatalogEntry, ConfiguratorField } from '../../types/product'

const vehicleSizeField: ConfiguratorField = {
  key: 'size',
  type: 'size',
  label: 'Tamano de vehiculo',
  required: true,
  options: [
    { value: 'S', label: 'S' },
    { value: 'M', label: 'M' },
    { value: 'L', label: 'L' },
    { value: 'XL', label: 'XL' },
  ],
}

const serviceField: ConfiguratorField = { key: 'variant', type: 'variant', label: 'Servicio', required: true, options: [] }

export const rotulacionEntries: CatalogEntry[] = [
  {
    id: 'rotulacion-basica',
    slug: 'rotulacion-basica-furgoneta',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion basica de furgoneta',
    description: 'Logo en puertas e informacion de contacto. Incluye material e instalacion. No incluye diseno.',
    shortDescription: 'Proyecto base de vehiculo con rango orientativo y cierre por presupuesto.',
    route: '#/servicios/rotulacion',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 180, max: 1000 },
    badge: 'Presupuesto',
    notes: ['Vinilo en color plano o impreso.'],
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-parcial',
    slug: 'rotulacion-parcial-furgoneta',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion parcial de furgoneta',
    description: 'Aplicacion por secciones. Mas economica que la integral y util para flotas.',
    shortDescription: 'Cobertura por secciones con estimacion de rango comercial.',
    route: '#/servicios/rotulacion',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 300, max: 1000 },
    badge: 'Presupuesto',
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-semi',
    slug: 'rotulacion-semi-integral',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion semi-integral',
    description: 'Laterales, traseros y bajos con microperforado trasero homologado.',
    shortDescription: 'Semi-wrap con lectura de rango y aprobacion comercial posterior.',
    route: '#/servicios/rotulacion',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 900, max: 2000 },
    badge: 'Presupuesto',
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
  {
    id: 'rotulacion-full-wrap',
    slug: 'rotulacion-full-wrap',
    kind: 'service',
    category: 'rotulacion',
    name: 'Rotulacion full wrap',
    description: 'Cubre la totalidad del vehiculo. Incluye material e instalacion. No incluye diseno.',
    shortDescription: 'Wrap integral con rango alto y aprobacion previa obligatoria.',
    route: '#/servicios/rotulacion',
    purchaseMode: 'quote',
    pricingMode: 'range',
    upload: { required: false, acceptedFormats: [...commonArtworkFormats] },
    configuratorFields: [serviceField, vehicleSizeField],
    legalNotes: defaultCommercialNoticeKeys,
    cta: { type: 'request_quote', href: '#/presupuesto?service=rotulacion', label: 'Solicitar presupuesto', serviceKey: 'rotulacion' },
    manualReviewRequired: true,
    range: { min: 1800, max: 3400 },
    badge: 'Presupuesto',
    notes: ['Duracion aproximada de 3 a 5 anos.'],
    catalogGroups: ['quote', 'gran-formato', 'services'],
    visualKey: 'vehicle',
  },
]
